### ISSUE TITLE
Tenant Org Search Card

### ISSUE THREAD

**Issue by zachdt** [leaseOTB/ui-components#10]
This will be the most common represenation of a tenant org, must include:

[Image] ---- [Name] --- [Member Count]
 --- [Short Description]

**Comment by zachdt** [comment]
Remember to wrap the card component in a mat-ui grid like this exactly

`<Grid item xs={12} sm={6} md={4}>{CARD COMPONENT}<Grid/>`

**Comment by Josh1794** [comment]
@zachdt  Do you have a placeholder image?

**Comment by zachdt** [comment]
I do not have if u can try to find an existing tenant orgs logo that would be great

**Comment by Josh1794** [comment]
Ok I was thinking to avoid copyright issues just using like a stock no profile pic kinda thing
